# Generated by Django 4.2 on 2023-04-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0003_alter_offer_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="items_in_stock",
            field=models.IntegerField(),
        ),
    ]
