# Generated by Django 4.2 on 2023-04-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=64)),
                ("description", models.CharField(max_length=256)),
            ],
        ),
    ]
