# Generated by Django 4.2 on 2023-04-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=256)),
                ("exp", models.DateTimeField(blank=True)),
            ],
        ),
    ]
